# Generated by Django 4.0.6 on 2024-03-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandler', '0002_uploadedfile_player_color_uploadedfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='player_color',
            field=models.CharField(max_length=10),
        ),
    ]
